#!/bin/bash
# DO NOT EDIT THIS FILE

ocamlbuild -use-ocamlfind main.cmo state.cmo command.cmo devCard.cmo gui.cmo ai.cmo player.cmo tile.cmo trade.cmo elements.cmo
if [[ $? -ne 0 ]]; then
  cat <<EOF
===========================================================
WARNING: Your code currently does not compile.
===========================================================
EOF
  exit 1
fi
